export enum AuditAction {
  LOGGED_IN = 'LOGGED_IN',
  LOGGED_OUT = 'LOGGED_OUT',
  RESUME_UPLOADED = 'RESUME_UPLOADED',
  RESUME_APPROVED = 'RESUME_APPROVED',
  RESUME_REJECTED = 'RESUME_REJECTED',
  GITHUB_SYNCED = 'GITHUB_SYNCED',
  PROJECT_PUBLISHED = 'PROJECT_PUBLISHED',
  PROJECT_HIDDEN = 'PROJECT_HIDDEN',
  DRAFT_SAVED = 'DRAFT_SAVED',
  DRAFT_PUBLISHED = 'DRAFT_PUBLISHED',
  VERSION_CREATED = 'VERSION_CREATED',
  VERSION_ROLLED_BACK = 'VERSION_ROLLED_BACK',
  IMAGE_UPLOADED = 'IMAGE_UPLOADED',
  IMAGE_DELETED = 'IMAGE_DELETED',
  AI_CALLED = 'AI_CALLED',
  AI_FAILED = 'AI_FAILED',
  SETTINGS_UPDATED = 'SETTINGS_UPDATED',
  THEME_CHANGED = 'THEME_CHANGED',
  FEATURE_FLAG_TOGGLED = 'FEATURE_FLAG_TOGGLED',
  PUBLIC_API_RATE_LIMITED = 'PUBLIC_API_RATE_LIMITED',
}

export type AuditSource = 'admin' | 'system' | 'github' | 'ai'

export interface AuditLog {
  id: string
  adminId?: string
  action: AuditAction
  metadata: Record<string, unknown>
  timestamp: string
  source: AuditSource
}
