export const QUERY_KEYS = {
  profile: ['profile'] as const,
  skills: ['skills'] as const,
  experience: ['experience'] as const,
  education: ['education'] as const,
  projects: ['projects'] as const,
  services: ['services'] as const,
  draft: ['draft'] as const,
  resume: ['resume'] as const,
  resumeDiff: ['resume', 'diff'] as const,
  githubRepos: ['github', 'repos'] as const,
  media: ['media'] as const,
  analytics: (range: string) => ['analytics', range] as const,
  settings: ['settings'] as const,
  theme: ['theme'] as const,
  notifications: ['notifications'] as const,
  versions: ['versions'] as const,
  audit: ['audit'] as const,
  health: ['health'] as const,
  auth: ['auth'] as const,
}
