import type { ThemeSlot } from '@/types/settings'

export const THEME_SLOTS: ThemeSlot[] = [
  {
    id: 'classic-dark',
    name: 'Classic Dark',
    primaryColor: '#0A0A0A',
    accentColor: '#6C63FF',
    fontFamily: 'Sora',
    borderRadius: '0.8rem',
    animationSpeed: '400ms',
    mode: 'dark',
  },
  {
    id: 'midnight-blue',
    name: 'Midnight Blue',
    primaryColor: '#0D1117',
    accentColor: '#58A6FF',
    fontFamily: 'Sora',
    borderRadius: '0.8rem',
    animationSpeed: '400ms',
    mode: 'dark',
  },
  {
    id: 'forest',
    name: 'Forest',
    primaryColor: '#1A1F1A',
    accentColor: '#5DB075',
    fontFamily: 'Sora',
    borderRadius: '0.8rem',
    animationSpeed: '400ms',
    mode: 'dark',
  },
  {
    id: 'warm-minimal',
    name: 'Warm Minimal',
    primaryColor: '#FAFAF8',
    accentColor: '#C17C4A',
    fontFamily: 'Sora',
    borderRadius: '0.8rem',
    animationSpeed: '400ms',
    mode: 'light',
  },
  {
    id: 'slate',
    name: 'Slate',
    primaryColor: '#1E293B',
    accentColor: '#94A3B8',
    fontFamily: 'Sora',
    borderRadius: '0.8rem',
    animationSpeed: '400ms',
    mode: 'dark',
  },
  {
    id: 'ink',
    name: 'Ink',
    primaryColor: '#FFFFFF',
    accentColor: '#EC4899',
    fontFamily: 'Sora',
    borderRadius: '0.8rem',
    animationSpeed: '400ms',
    mode: 'light',
  },
]
